typography_spectrum: 0.8980307404417545
color:
  brandColors:
    - '#d6e1e2'
    - '#1a1a20'
    - '#ffe54c'
    - '#91b4b6'
    - '#5d7175'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05694
analytics:
  google: null
  facebook: null
  twitter: null
name: I am Foodie
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
favicon: null
purpose: []
