name: FoodandDrink
favicon: null
layout_spectrum: 0.4282816695049405
typography_spectrum: 0.8980307404417545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5178112096618861
  lightness: 0.30740053695626557
  saturation: 0.3536092347931117
  rhythmicContrast: 0.6219832592178136
purpose: []
