name: FoodandDrink
favicon: null
layout_spectrum: 0.05694
typography_spectrum: 0.8980307404417545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f75490'
    - '#203354'
    - '#a4f5ee'
    - '#dd86ae'
    - '#bec3d1'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
