name: FoodandDrink
favicon: null
layout_spectrum: 0.05694
typography_spectrum: 0.8980307404417545
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6e1e2'
    - '#1a1a20'
    - '#ffe54c'
    - '#91b4b6'
    - '#5d7175'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
